import { StyleSheet } from 'react-native';

export default StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#eef9f0',
  },
  scrollContent: {
    padding: 18,
    gap: 14,
    paddingBottom: 40,
    maxWidth: 800,
    width: '100%',
    alignSelf: 'center',
  },
  heroCard: {
    borderRadius: 24,
    padding: 18,
    backgroundColor: '#ffffff',
    borderWidth: 1,
    borderColor: '#bbf7d0',
    boxShadow: '0 18px 34px rgba(16, 185, 129, 0.12)',
    overflow: 'hidden',
  },
  heroTopRow: {
    gap: 14,
  },
  eyebrow: {
    color: '#15803d',
    fontSize: 11,
    fontWeight: '800',
    letterSpacing: 1.2,
    textTransform: 'uppercase',
    marginBottom: 6,
  },
  panelCardSpecial: {
    backgroundColor: '#fffbeb',
    borderColor: '#fde68a',
    borderWidth: 2,
    borderRadius: 20,
    padding: 16,
    marginVertical: 12,
    boxShadow: '0 10px 15px rgba(245, 158, 11, 0.1)',
  },
  panelTitleSpecial: {
    color: '#92400e',
    fontSize: 16,
    fontWeight: '900',
  },
  panelContent: {
    color: '#475569',
    fontSize: 14,
    marginTop: 10,
    lineHeight: 20,
  },

  title: {
    color: '#052e16',
    fontSize: 20,
    fontWeight: '900',
    lineHeight: 28,
  },
  subtitle: {
    color: '#365314',
    marginTop: 4,
    fontSize: 14,
    lineHeight: 20,
  },
  sectionTitleEmbedded: {
    color: '#052e16',
    fontSize: 18,
    fontWeight: '900',
    marginBottom: 8,
  },
  sectionDescription: {
    color: '#475569',
    fontSize: 14,
    lineHeight: 18,
    marginTop: 4,
  },
  categoryTitle: {
    fontSize: 14,
    fontWeight: '800',
    marginBottom: 8,
    marginTop: 4,
  },
  dangerText: {
    color: '#dc2626',
  },
  safeText: {
    color: '#16a34a',
  },
  inlineSectionHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: 12,
  },
  tanimlaButton: {
    backgroundColor: '#0f766e',
    paddingVertical: 6,
    paddingHorizontal: 12,
    borderRadius: 8,
  },
  tanimlaButtonText: {
    color: '#ffffff',
    fontSize: 12,
    fontWeight: '700',
  },

  liveBadge: {
    alignSelf: 'flex-start',
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    borderRadius: 999,
    paddingVertical: 8,
    paddingHorizontal: 12,
    backgroundColor: '#dcfce7',
  },
  liveDot: {
    width: 8,
    height: 8,
    borderRadius: 4,
    backgroundColor: '#16a34a',
  },
  liveText: {
    color: '#166534',
    fontSize: 12,
    fontWeight: '800',
  },
  liveActionsRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
    marginTop: 8,
    flexWrap: 'wrap',
  },
  affectedTrigger: {
    backgroundColor: '#ffffff',
    borderWidth: 1,
    borderColor: '#fecaca',
    paddingVertical: 10,
    paddingHorizontal: 16,
    borderRadius: 14,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
    boxShadow: '0 8px 20px rgba(225, 29, 72, 0.08)',
  },
  affectedTriggerText: {
    color: '#9f1239',
    fontSize: 13,
    fontWeight: '800',
  },
  affectedTriggerIcon: {
    fontSize: 16,
  },
  statCard: {
    flexGrow: 1,
    minWidth: 95,
    borderRadius: 16,
    paddingVertical: 12,
    paddingHorizontal: 12,
    backgroundColor: '#f0fdf4',
    borderWidth: 1,
    borderColor: '#bbf7d0',
  },
  statValue: {
    color: '#14532d',
    fontSize: 18,
    fontWeight: '900',
  },
  statLabel: {
    color: '#4b5563',
    marginTop: 2,
    fontSize: 11,
  },
  detailsGrid: {
    backgroundColor: '#f8fafc',
    borderRadius: 18,
    padding: 16,
    borderWidth: 1,
    borderColor: '#e2e8f0',
    marginTop: 12,
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 12,
  },
  detailItem: {
    width: '47%',
  },
  detailLabel: {
    color: '#64748b',
    fontSize: 11,
    fontWeight: '800',
    textTransform: 'uppercase',
    letterSpacing: 0.5,
    marginBottom: 4,
  },
  detailValue: {
    color: '#1e293b',
    fontSize: 14,
    fontWeight: '700',
  },
  sectionHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 12,
    marginTop: 6,
  },
  sectionTitle: {
    color: '#052e16',
    fontSize: 18,
    fontWeight: '900',
  },
  sectionChip: {
    color: '#166534',
    backgroundColor: '#dcfce7',
    paddingVertical: 7,
    paddingHorizontal: 12,
    borderRadius: 999,
    fontSize: 12,
    fontWeight: '800',
    textTransform: 'capitalize',
  },
  peopleGrid: {
    gap: 12,
  },
  personCard: {
    borderRadius: 20,
    padding: 14,
    backgroundColor: '#ffffff',
    borderWidth: 1,
    borderColor: '#d1fae5',
    boxShadow: '0 14px 24px rgba(34, 197, 94, 0.10)',
  },
  personPhotoWrap: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: 10,
  },
  personPhoto: {
    width: 70,
    height: 70,
    borderRadius: 18,
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.65)',
  },
  personPhotoText: {
    color: '#ffffff',
    fontSize: 22,
    fontWeight: '900',
    letterSpacing: 0.8,
  },
  badgeWrap: {
    paddingVertical: 7,
    paddingHorizontal: 10,
    borderRadius: 999,
    backgroundColor: '#f0fdf4',
    borderWidth: 1,
    borderColor: '#bbf7d0',
  },
  badgeText: {
    color: '#166534',
    fontSize: 11,
    fontWeight: '900',
  },
  personName: {
    color: '#052e16',
    fontSize: 16,
    fontWeight: '900',
  },
  personLocation: {
    color: '#166534',
    fontSize: 13,
    fontWeight: '700',
    marginTop: 3,
  },
  personStatus: {
    color: '#475569',
    marginTop: 8,
    fontSize: 14,
    lineHeight: 20,
  },
  colorCaptionRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    marginTop: 12,
  },
  colorDot: {
    width: 10,
    height: 10,
    borderRadius: 5,
  },
  colorCaption: {
    color: '#64748b',
    fontSize: 12,
    flex: 1,
  },
  actionRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 10,
  },
  actionCard: {
    flexGrow: 1,
    minWidth: 100,
    borderRadius: 16,
    backgroundColor: '#dcfce7',
    padding: 14,
    borderWidth: 1,
    borderColor: '#86efac',
  },
  actionTitle: {
    color: '#14532d',
    fontSize: 14,
    fontWeight: '900',
    marginBottom: 4,
  },
  actionDescription: {
    color: '#166534',
    fontSize: 12,
    lineHeight: 18,
  },
  // Modal Styles
  modalOverlay: {
    flex: 1,
    backgroundColor: 'rgba(0,0,0,0.5)',
    justifyContent: 'center',
    alignItems: 'center',
    padding: 20,
  },
  modalContent: {
    width: '100%',
    backgroundColor: '#ffffff',
    borderRadius: 24,
    padding: 24,
    gap: 16,
  },
  modalTitle: {
    fontSize: 20,
    fontWeight: '900',
    color: '#0f172a',
  },
  modalButton: {
    backgroundColor: '#0f766e',
    paddingVertical: 14,
    borderRadius: 12,
    alignItems: 'center',
  },
  modalButtonSecondary: {
    backgroundColor: '#f1f5f9',
    paddingVertical: 14,
    borderRadius: 12,
    alignItems: 'center',
  },
  modalButtonText: {
    color: '#ffffff',
    fontSize: 16,
    fontWeight: '700',
  },
  modalButtonTextSecondary: {
    color: '#475569',
    fontSize: 16,
    fontWeight: '700',
  },
  modalHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'flex-start',
    marginBottom: 16,
  },
  modalTitleContainer: {
    flex: 1,
  },
  modalSubtitle: {
    fontSize: 14,
    color: '#64748b',
    marginTop: 4,
    lineHeight: 20,
    fontWeight: '500',
  },
  closeButton: {
    width: 32,
    height: 32,
    borderRadius: 16,
    backgroundColor: '#f1f5f9',
    justifyContent: 'center',
    alignItems: 'center',
  },
  closeButtonText: {
    fontSize: 18,
    color: '#64748b',
    fontWeight: '800',
  },
  modalScroll: {
    marginVertical: 4,
  },
  modalPersonCard: {
    backgroundColor: '#ffffff',
    borderRadius: 20,
    padding: 16,
    marginBottom: 12,
    borderWidth: 1,
    borderColor: '#f1f5f9',
    boxShadow: '0 4px 12px rgba(0,0,0,0.03)',
  },
  modalPersonInfo: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 14,
  },
  personAvatar: {
    width: 48,
    height: 48,
    borderRadius: 14,
    justifyContent: 'center',
    alignItems: 'center',
    borderWidth: 2,
    borderColor: '#ffffff',
    boxShadow: '0 4px 10px rgba(0,0,0,0.1)',
  },
  personAvatarText: {
    color: '#ffffff',
    fontSize: 18,
    fontWeight: '900',
  },
  modalPersonName: {
    fontSize: 16,
    fontWeight: '900',
    color: '#0f172a',
  },
  modalPersonStatus: {
    fontSize: 13,
    color: '#e11d48',
    fontWeight: '800',
    marginTop: 2,
  },
  modalPersonLocationWrap: {
    marginTop: 12,
    paddingTop: 12,
    borderTopWidth: 1,
    borderTopColor: '#f1f5f9',
  },
  modalPersonLocation: {
    fontSize: 12,
    color: '#64748b',
    fontWeight: '700',
    letterSpacing: 0.2,
  },
  // Form Styles
  inputGroup: {
    marginBottom: 20,
  },
  inputLabel: {
    fontSize: 13,
    fontWeight: '800',
    color: '#334155',
    marginBottom: 8,
    marginLeft: 4,
  },
  premiumInput: {
    backgroundColor: '#ffffff',
    borderWidth: 1,
    borderColor: '#e2e8f0',
    borderRadius: 14,
    padding: 14,
    fontSize: 14,
    color: '#0f172a',
    fontWeight: '600',
    boxShadow: '0 2px 4px rgba(0,0,0,0.02)',
  },
  dropdownWrap: {
    flexDirection: 'row',
    paddingVertical: 4,
  },
  personChip: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#ffffff',
    borderWidth: 1,
    borderColor: '#e2e8f0',
    borderRadius: 12,
    padding: 8,
    paddingRight: 12,
    gap: 8,
  },
  personChipSelected: {
    borderColor: '#15803d',
    backgroundColor: '#f0fdf4',
    borderWidth: 2,
  },
  chipAvatar: {
    width: 24,
    height: 24,
    borderRadius: 8,
    justifyContent: 'center',
    alignItems: 'center',
  },
  chipAvatarText: {
    color: '#ffffff',
    fontSize: 10,
    fontWeight: '900',
  },
  chipName: {
    fontSize: 13,
    fontWeight: '700',
    color: '#475569',
  },
  chipNameSelected: {
    color: '#15803d',
  },
  modalFooterActions: {
    flexDirection: 'row',
    gap: 12,
    marginTop: 10,
  },
  // FAB Styles
  fab: {
    position: 'absolute',
    right: 24,
    bottom: 24,
    width: 64,
    height: 64,
    borderRadius: 32,
    backgroundColor: '#15803d',
    justifyContent: 'center',
    alignItems: 'center',
    elevation: 8,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.3,
    shadowRadius: 6,
    zIndex: 1000,
  },
  fabIcon: {
    color: '#ffffff',
    fontSize: 32,
    fontWeight: '300',
  },
  // Pill Menu Styles
  fabMenuOverlay: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    backgroundColor: 'rgba(0,0,0,0.1)', // Subtle dim
    zIndex: 999,
  },
  fabMenu: {
    position: 'absolute',
    right: 24,
    bottom: 100,
    alignItems: 'flex-end',
    gap: 12,
    zIndex: 1001,
  },
  menuItemPill: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#ffffff',
    paddingVertical: 10,
    paddingHorizontal: 16,
    borderRadius: 30,
    borderWidth: 1,
    borderColor: '#e2e8f0',
    elevation: 4,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 3,
  },
  menuItemPillPrimary: {
    backgroundColor: '#15803d',
    borderColor: '#15803d',
  },
  menuItemText: {
    color: '#334155',
    fontSize: 14,
    fontWeight: '700',
    marginRight: 8,
  },
  menuItemTextPrimary: {
    color: '#ffffff',
  },
  menuItemIcon: {
    fontSize: 18,
  },
  menuItemIconPrimary: {
    // Optional: add specific icon style if needed
  },
});
