import { StyleSheet } from 'react-native';

export default StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#eef9f0',
  },
  topGlow: {
    position: 'absolute',
    top: -120,
    right: -80,
    width: 260,
    height: 260,
    borderRadius: 999,
    backgroundColor: '#bbf7d0',
    opacity: 0.45,
  },
  headerWrap: {
    paddingTop: 58,
    paddingBottom: 18,
    paddingHorizontal: 20,
    borderBottomWidth: 1,
    borderBottomColor: '#bbf7d0',
  },
  brandEyebrow: {
    color: '#15803d',
    fontSize: 11,
    fontWeight: '800',
    letterSpacing: 1.1,
    textTransform: 'uppercase',
  },
  brandName: {
    marginTop: 6,
    color: '#0f766e',
    fontSize: 34,
    fontWeight: '900',
    letterSpacing: 0.6,
  },
  scrollContent: {
    width: '100%',
    maxWidth: 820,
    alignSelf: 'center',
    paddingHorizontal: 18,
    paddingTop: 20,
    paddingBottom: 36,
    gap: 14,
  },
  heroCard: {
    borderRadius: 24,
    padding: 20,
    backgroundColor: '#ffffff',
    borderWidth: 1,
    borderColor: '#bbf7d0',
    boxShadow: '0 18px 34px rgba(16, 185, 129, 0.12)',
    overflow: 'hidden',
  },
  heroTitle: {
    color: '#052e16',
    fontSize: 32,
    fontWeight: '900',
    lineHeight: 38,
  },
  heroSubtitle: {
    marginTop: 10,
    color: '#365314',
    fontSize: 15,
    lineHeight: 22,
    textAlign: 'justify',
  },
  metricsRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 10,
    marginTop: 16,
    marginBottom: 18,
  },
  metricCard: {
    flexGrow: 1,
    minWidth: 98,
    borderRadius: 14,
    paddingVertical: 10,
    paddingHorizontal: 12,
    backgroundColor: '#f0fdf4',
    borderWidth: 1,
    borderColor: '#bbf7d0',
  },
  metricValue: {
    color: '#14532d',
    fontSize: 18,
    fontWeight: '900',
  },
  metricLabel: {
    color: '#4b5563',
    marginTop: 2,
    fontSize: 11,
  },
  loginButton: {
    backgroundColor: '#0f766e',
    paddingVertical: 14,
    borderRadius: 14,
    alignItems: 'center',
    boxShadow: '0 12px 22px rgba(15, 118, 110, 0.24)',
  },
  loginButtonText: {
    color: '#ffffff',
    fontSize: 16,
    fontWeight: '800',
    letterSpacing: 0.4,
  },
  card: {
    width: '100%',
    borderRadius: 22,
    backgroundColor: '#ffffff',
    padding: 18,
    borderWidth: 1,
    borderColor: '#bbf7d0',
    boxShadow: '0 14px 24px rgba(34, 197, 94, 0.10)',
  },
  cardHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 10,
    gap: 10,
  },
  cardIcon: {
    fontSize: 22,
  },
  cardTitle: {
    color: '#052e16',
    fontSize: 18,
    fontWeight: '800',
  },
  cardText: {
    color: '#475569',
    fontSize: 14,
    lineHeight: 21,
    textAlign: 'justify',
  },
  warningCard: {
    borderRadius: 22,
    padding: 18,
    backgroundColor: '#fffbeb',
    borderWidth: 2,
    borderColor: '#fde68a',
    boxShadow: '0 10px 15px rgba(245, 158, 11, 0.1)',
  },
  warningCardTitle: {
    color: '#92400e',
    fontSize: 18,
    fontWeight: '900',
  },
  warningCardText: {
    color: '#475569',
    marginTop: 2,
    fontSize: 14,
    lineHeight: 21,
    textAlign: 'justify',
  },
  bottomSpacer: {
    height: 120,
  },
  bottomContainer: {
    position: 'absolute',
    left: 0,
    right: 0,
    bottom: 0,
    paddingHorizontal: 18,
    paddingTop: 12,
    paddingBottom: 24,
    backgroundColor: 'rgba(238, 249, 240, 0.9)',
  },
  emergencyButton: {
    backgroundColor: '#dc2626',
    borderRadius: 16,
    paddingVertical: 18,
    alignItems: 'center',
    borderWidth: 2,
    borderColor: '#b91c1c',
    boxShadow: '0 14px 24px rgba(220, 38, 38, 0.25)',
  },
  emergencyButtonText: {
    color: '#ffffff',
    fontSize: 20,
    fontWeight: '900',
    letterSpacing: 0.8,
  },
});
